### ISSUE TITLE
dart: libbullet-dev double precision 

### ISSUE THREAD

**Issue by eastskykang** [leggedrobotics/SimBenchmark#10]
does ```libbullet-dev``` support double precision?

**Comment by jslee02** [comment]
For clarification, do you refer to `libdart6-collision-bullet-dev` or `libbullet-dev`? If you mean `libbullet-dev`, it isn't built with the double precision option by looking at the [debian file here](https://packages.ubuntu.com/bionic/libbullet-dev) for example. Also, as `libdart6-collision-bullet-dev` is built on `libbullet-dev`, DART inherently uses Bullet with single precision unless you build them from source.

**Comment by eastskykang** [comment]
@jslee02 thank you so much for your quick response. We are now using Bullet built from the source with double precision but I got an error as I turned on ```DBT_USE_DOUBLE_PRECISION``` from my docker container using ```libbullet-dev```. 

ps. Is ```libdart6-collision-bullet-dev``` enough to use bullet-collision for dart? It would be nice to change [install manual](http://dartsim.github.io/install_dart_on_ubuntu.html) if it's the case.

**Comment by jslee02** [comment]
> I got an error as I turned on DBT_USE_DOUBLE_PRECISION from my docker container using libbullet-dev

This is presumably because `libbullet-dev` isn't built with `DBT_USE_DOUBLE_PRECISION` turned on.

> Is libdart6-collision-bullet-dev enough to use bullet-collision for dart?

`libdart6-collision-bullet-dev` is an necessary component to use bullet collision detection in DART, but you may need other components as well. I generally recommend installing all the components using `libdart6-all-dev`.

**Comment by eastskykang** [comment]
@jslee02 okay thank you for your suggestion. I will close this issue.
